# Generated by Django 5.2.9 on 2025-12-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_message_seen_message_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delivered',
        ),
        migrations.AlterField(
            model_name='message',
            name='is_saved',
            field=models.BooleanField(default=True),
        ),
    ]
