# Generated by Django 5.2.9 on 2025-12-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_message_delivered_alter_message_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_saved',
        ),
        migrations.RemoveField(
            model_name='message',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='message',
            name='saved_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='saved_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
